### ISSUE TITLE
Should we use "*" instead of ""?

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-add/draft-ietf-add-split-horizon-authority#21]
In draft-08, a claimed subdomain is represented by stripping off the suffix that matches the parent (e.g. "payroll.internal.example.com" - "example.com" = "payroll.internal.").  To claim the entire parent zone, the claimed subdomain is "." (or the empty string, in contexts where the terminal "." is omitted, such as PvD JSON).  This is sort of logical but also a bit strange, and might require special-case handling in code.

If we need a special case, maybe we should be more explicit and use "*" instead.

**Comment by danwing** [comment]
Agreed that "*" is clearer to people and code.

-d

**Comment by tireddy2** [comment]
Fixed in 06 version.
