### ISSUE TITLE
Consider recommending the internal-only subzone configuration

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-add/draft-ietf-add-split-horizon-authority#23]
The draft supports both "internal-only subzone" configurations (where secret labels are under a non-sensitive label) and "mixed zone" configurations, where secret labels are mixed with public labels at the same level in the zone.

We might want to recommend the "subzone" configuration for new deployments, if only because it reduces the frequency of changes to the Verification Record.

Credit to @mcr

**Comment by tireddy2** [comment]
Fixed in 06 version.
