### ISSUE TITLE
Use documentation address

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#26]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L520

**Comment by Kevsy** [comment]
I can't see an example address for an external resolver in the documentation, so it's probably best just to remove the example. Fixed in #38
