### ISSUE TITLE
normative references

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#27]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L729

Not sure this is normative.

**Comment by Kevsy** [comment]
Thanks, fixed in #37  (I also moved the other referenced I-D to 'informative references')
