### ISSUE TITLE
Use a realistic expiry time

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#28]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L459

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
