### ISSUE TITLE
reasonable split-horizon

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#30]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L202C1-L203C56

Not sure how to assess what is reasonable. 

Not sure I would maintain this requirement unless we have a clear technical characterization of how to assess the requirement is met.

**Comment by tireddy2** [comment]
We can update it say: The specification can represent and authorize a typical Split DNS zone structure.

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
