### ISSUE TITLE
notation

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#31]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L243C42-L243C44

Add a note about the notation used in this bullet as not all readers may be familiar with.

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
