### ISSUE TITLE
RDM

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#33]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L288C55-L288C59

Please expand to: Replay Detection Method (RDM)

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
