### ISSUE TITLE
RFC8598

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#34]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L630C13-L630C35

It would be worth to indicate whether the validation procedure is worth in the presence of rfc8598.

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
