### ISSUE TITLE
RFC8762

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#35]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L268C23-L268C30

Please update the example to comply with the structure in https://www.rfc-editor.org/rfc/rfc8792#name-folded-structure

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
