### ISSUE TITLE
secure transport vs. encrypted transport

### ISSUE THREAD

**Issue by boucadair** [ietf-wg-add/draft-ietf-add-split-horizon-authority#36]
https://github.com/ietf-wg-add/draft-ietf-add-split-horizon-authority/blob/2dc4e5f15eb7c614b5237ac1565d73253bcc4130/draft-ietf-add-split-horizon-authority.xml#L339C29-L339C47

This is the only use of "secure transport" in the doc, while "encrypted transport" is defined and used in other parts part the doc. You may change this occurrence as well for the sake of consistency.

**Comment by tireddy2** [comment]
Fixed in draft-ietf-add-split-horizon-authority-05 revision.
