### ISSUE TITLE
Gen-ART review comments

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-add/draft-ietf-add-split-horizon-authority#59]
Courtesy of @mallory

> The opening sentence for Section 5 is a bit premature, redundant and leads to
> some confusion, "To establish its authority over some DNS zone, a..." I would
> suggest simply removing this opening clause because what is described in that
> paragraph is an essential component of establishing authority but not the
> action. The following paragraph begins the same way because it is where the
> establishing action is described.
> 
> Furthermore in the penultimate paragraph (bullet points notwithstanding) of
> Section 5 again the opening phrase is used, "To establish its authority, the
> network..." Suggest removing this and replacing it with a simple "Then, the
> network..." to denote that the paragraph goes on to describe the next step in
> the establishment of authority.
> 
> In 8.1.2, Step 3: Genuinely unsure if the opening sentence is describing
> something causal, "The DNSSEC validation is successful and the token matches,
> so this Authorization Claim is validated," and if so then it might rather be
> re-phrased "If..., then..."  Additionally the next sentence begins with "When"
> when subtly it should begin with "Once," where the latter implies causation and
> the former is typically used only if the timing of an action is important.
> 
> In Security Considerations advice is given to local resolvers when naming their
> ADN, however the advice is somewhat confusing because I think it might be
> inaccurate. It says, "  To avoid leakage, local resolvers..." but what it's
> really saying is that leakage is possible and so to avoid negative impacts of
> that leakage the local resolvers... Please check my (mis)understanding and
> better clarify what the risk is and what this mitigation can actually achieve.

**Comment by boucadair** [comment]
The comments were addressed in -13. Please close this one.
